Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1904"

   # Install Docker
  #config.vm.provision :docker

  # Install Docker Compose
  #config.vm.provision :docker_compose


  # Setup consul on all the machines
  config.vm.provision "shell", path: "consul.setup.sh", privileged: false

  config.vm.define "consul-server" do |cs|
    cs.vm.hostname = "consul-server"
    cs.vm.network "private_network", ip: "172.20.20.41"
  end

  config.vm.define "lb" do |loadbalancer|
  loadbalancer.vm.hostname = "lb"
    loadbalancer.vm.network "private_network", ip: "172.20.20.11"
  end

  (1..2).each do |i|
    config.vm.define "tserver#{i}" do |server|
    server.vm.hostname = "tserver#{i}"
      server.vm.network "private_network", ip: "172.20.20.2#{i}"
    end
  end

  (1..2).each do |i|
    config.vm.define "dserver#{i}" do |server|
    server.vm.hostname = "dserver#{i}"
      server.vm.network "private_network", ip: "172.20.20.3#{i}"
    end
  end

end
