Vagrant.configure("2") do |config|
  #config.vm.box = "wesmcclure/ubuntu1404-docker"
  #config.vm.box = "Slach/kubernetes-docker"
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "consul.setup.sh", privileged: false
  config.vm.provision "shell", path: "envoy.setup.sh", privileged: false

  config.vm.provision :docker do |d|
    d.pull_images "busybox"
#    d.run "simple-echo",
#      image: "busybox",
#      args: "-p 8080:8080 -v /usr/bin/dumb-init:/dumb-init:ro --entrypoint=/dumb-init",
#      cmd: "nc -p 8080 -l -l -e echo hello world!"
  end

  #config.vm.network :forwarded_port, guest: 8080, host: 8080


  config.vm.define "consul-server" do |cs|
    cs.vm.hostname = "consul-server"
    cs.vm.network "private_network", ip: "172.20.20.41"
  end

  (1..1).each do |i|
    config.vm.define "tick#{i}" do |tick|
      tick.vm.hostname = "tick#{i}"
      tick.vm.network "private_network", ip: "172.20.20.2#{i}"
    end
  end

  (1..1).each do |i|
    config.vm.define "direction#{i}" do |direction|
      direction.vm.hostname = "direction#{i}"
      direction.vm.network "private_network", ip: "172.20.20.3#{i}"
    end
  end

  config.vm.define "egress-server" do |es|
    es.vm.hostname = "egress-server"
    es.vm.network "private_network", ip: "172.20.20.51"
  end

end
